# Generated by Django 4.2.6 on 2023-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
