# Generated by Django 4.2.6 on 2023-12-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
