# Generated by Django 4.2.6 on 2023-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_product_type'),
        ('accounts', '0005_alter_profile_img'),
        ('cart', '0004_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
