# Generated by Django 4.2.6 on 2023-12-05 08:07

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_product_type'),
        ('cart', '0005_rename_order_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(to='home.product',on_delete=django.db.models.deletion.CASCADE),
        ),
    ]
