# Generated by Django 4.2.6 on 2023-12-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_img'),
        ('cart', '0009_alter_orders_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
