# Generated by Django 4.2.6 on 2023-12-18 04:44

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_product_type'),
        ('cart', '0017_alter_orders_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(to='home.product',on_delete=django.db.models.deletion.CASCADE),
        ),
    ]
