# Generated by Django 4.2.6 on 2023-12-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_remove_cartitem_product_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
