# Generated by Django 4.2.6 on 2023-12-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='quantit',
        ),
    ]
