# Generated by Django 4.2.6 on 2023-12-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_rename_quantity_cartitem_quantit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantit',
            new_name='quantity',
        ),
    ]
