# Generated by Django 4.2.6 on 2023-12-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_product_type'),
        ('cart', '0029_remove_orders_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('product', 'status')},
        ),
    ]
