# Generated by Django 4.2.6 on 2023-12-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_product_type'),
        ('accounts', '0005_alter_profile_img'),
        ('cart', '0031_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('product', 'profile', 'status', 'quantity')},
        ),
    ]
