# Generated by Django 4.2.6 on 2023-12-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
    ]
